### ISSUE TITLE
Issue: Selecting "Active Directory Option" In Ceph Deploy does not configure domain join when running SMB playbook

### ISSUE THREAD

**Issue by bailey-97** [45Drives/cockpit-ceph-deploy#5]
**Bug Info**
When configuring hosts/inventory files in Ceph Deploy, selecting the Active Directory option for SMB does not update the SMB inventory file to check for domain joins, and thus when the playbook finishes SMB is setup without Active Directory integration.

It leaves the domain_member value set to false in the smbs.yml file, which then causes the playbook to function as if it's local users selected instead of active directory (located line 16 in /usr/share/ceph-ansible/group_vars/smbs.yml):

# Roles
samba_server: true
samba_cluster: true
**domain_member: false**

Once the playbook finishes it does deploy SMB without failing the playbook, however it does not have the Active Directory configuration.

**To Reproduce**

When configuring SMB options within Ceph Deploy, select the Active Directory option, then generate the SMBs yml file.

**A clear and concise description of what you expected to happen.**

Running the playbook joins SMB CTDB cluster to Active Directory.

**Screenshots**

![domain](https://user-images.githubusercontent.com/88982700/143059915-5c45ce3c-8cf6-43a3-a187-7bbdc413797a.gif)

**Console Output**

N/A

**Client Side**

**Desktop (please complete the following information):**

OS: Windows
Browser: Chrome
Version: Version 95.0.4638.69 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

Device: N/A
OS: N/A
Browser: N/A
Version: N/A

**Server Side**
OS: Ubuntu 20.04
Cockpit Version: 250.1.1-1

**Additional context**

N/A

**Comment by markdhooper** [comment]
That boys right there is how you submit an issue. ;)
I'll take a look-see shortly.

**Comment by markdhooper** [comment]
I found the issue, I was performing a search in the template smbs.yml file thinking that I was searching each line when I was in fact searching each character... `smbs_file.read()` vs `smbs_file.readlines()`, so my search was never finding and modifying the value of `domain_member`. [made a quick fix](https://github.com/45Drives/cockpit-ceph-deploy/commit/09c639ba84697d2d7ca970298671ed893b25ba55)

This issue is fixed with the 1.0.1-8 release, It is on the stable repos now, so just install the latest package.

**Comment by bailey-97** [comment]
awesome, thank you sir
