### ISSUE TITLE
Ceph deploy - Dashboard step problem

### ISSUE THREAD

**Issue by espats** [45Drives/cockpit-ceph-deploy#7]
Since Ceph Github repository changes(updates) early February 2022 Grafana json files have changed location. Trying to run Dashboard step at some point shows errors like this:
```
failed: [bigstore2] (item=radosgw-detail.json) => changed=false 
  ansible_loop_var: item
  dest: /etc/grafana/dashboards/ceph-dashboard/radosgw-detail.json
  elapsed: 0
  item: radosgw-detail.json
  msg: Request failed
  response: 'HTTP Error 404: Not Found'
  status_code: 404
  url: https://raw.githubusercontent.com/ceph/ceph/master/monitoring/grafana/dashboards/radosgw-detail.json
```
I have Cluster set up on Ubuntu OS.
Changing file `/usr/share/ceph-ansible/roles/ceph-grafana/tasks/configure_grafana.yml` and running step again managed to complete Dashoard step. Cahanges files 39 line:
From: `url: "https://raw.githubusercontent.com/ceph/ceph/{{ grafana_dashboard_version }}/monitoring/grafana/dashboards/{{ item }}"`
To: `url: "https://github.com/ceph/ceph/tree/master/monitoring/ceph-mixin/dashboards_out/{{ item }}"`

This is not the most elegant way, but it got it done.

**Comment by markdhooper** [comment]
So this is happening due to another package ceph-ansible-45d. 
Which is our own fork of ceph-ansible. We will update our playbooks for that package. 
That `radosgw-detail.json` file should be on the Admin node ever since we added the option for using offline repos for our air-gapped customers, so we'll modify our playbooks to point to that instead of the github link.

We'll patch ceph-ansible-45d and release a fix shortly. We'll let you know here when that is done. 

Thanks for letting us know!

**Comment by markdhooper** [comment]
That playbook is now updated in [ceph-ansible-45d_5.2.9-1](https://repo.45drives.com/debian/pool/main/c/ceph-ansible-45d/ceph-ansible-45d_5.2.9-1focal_all.deb)

`apt update`
`apt install ceph-ansible-45d`

should get you going using your package manager on the admin node.
